const { adminAuth } = require('../config/firebase');
const eventPublisher = require('../events/EventPublisher');
const jwt = require('jsonwebtoken');

class AuthService {
  /**
   * Signs in with email/password through Firebase Authentication, then runs the
   * same verified-token login flow used by other clients.
   */
  async LoginWithEmail(email, password) {
    const apiKey = process.env.FIREBASE_WEB_API_KEY;
    if (!apiKey) throw new Error("Firebase Web API key is not configured.");

    const response = await fetch(
      `https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=${encodeURIComponent(apiKey)}`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email, password, returnSecureToken: true })
      }
    );

    const data = await response.json();
    if (!response.ok || !data.idToken) {
      const firebaseCode = data?.error?.message || '';
      const friendlyErrors = {
        INVALID_LOGIN_CREDENTIALS: 'Invalid email or password.',
        EMAIL_NOT_FOUND: 'Invalid email or password.',
        INVALID_PASSWORD: 'Invalid email or password.',
        USER_DISABLED: 'This account has been disabled.',
        TOO_MANY_ATTEMPTS_TRY_LATER: 'Too many attempts. Please try again later.'
      };
      throw new Error(friendlyErrors[firebaseCode] || 'Unable to sign in.');
    }

    const result = await this.Login(data.idToken);
    return {
      ...result,
      refreshToken: data.refreshToken,
      expiresIn: Number(data.expiresIn) || 3600
    };
  }

  /**
   * Registers a new user using Firebase Admin SDK.
   * @param {string} email 
   * @param {string} password 
   * @returns {Object} The created user record
   */
  async Register(email, password) {
    if (!adminAuth) throw new Error("Firebase Admin not configured.");
    
    try {
      const userRecord = await adminAuth.createUser({
        email,
        password,
      });

      // Emit event
      await eventPublisher.publish('UserRegistered', {
        uid: userRecord.uid,
        email: userRecord.email,
      });

      return userRecord;
    } catch (error) {
      this.handleAuthError(error);
    }
  }

  /**
   * Logs in a user via a client-provided Firebase ID token.
   * The client (e.g. Unity) calls signInWithEmailAndPassword(), gets the ID token, 
   * and sends it to this backend method to initialize the session.
   * @param {string} idToken 
   * @returns {Object} User info and tokens
   */
  async Login(idToken) {
    if (!adminAuth) throw new Error("Firebase Admin not configured.");

    try {
      const decodedToken = await adminAuth.verifyIdToken(idToken);
      
      const payload = {
        uid: decodedToken.uid,
        email: decodedToken.email
      };

      // Emit event
      await eventPublisher.publish('UserLoggedIn', payload);

      return {
        user: payload,
        token: idToken,
      };
    } catch (error) {
      throw new Error("Invalid or expired ID Token.");
    }
  }

  /**
   * Processes Google Sign-In.
   * Since popups are client-side only, this method expects the Firebase ID Token
   * generated by the client after successful Google login.
   * @param {string} idToken 
   */
  async LoginWithGoogle(idToken) {
    if (!adminAuth) throw new Error("Firebase Admin not configured.");

    try {
      // Verify the ID token sent from the client
      const decodedToken = await adminAuth.verifyIdToken(idToken);
      
      const payload = {
        uid: decodedToken.uid,
        email: decodedToken.email,
        provider: 'google.com'
      };

      // Emit event
      await eventPublisher.publish('UserLoggedIn', payload);

      // In a more complex setup, we could issue our own JWT here. 
      // For now, we just validate and return success.
      return {
        user: payload,
        token: idToken // Returning the same token, or we could generate our own
      };
    } catch (error) {
      throw new Error("Invalid or expired Google ID Token.");
    }
  }

  /**
   * Logs out the user.
   * Revokes the user's refresh tokens in Firebase, enforcing re-authentication.
   * @param {string} uid 
   */
  async Logout(uid) {
    if (!adminAuth) throw new Error("Firebase Admin not configured.");
    
    try {
      if (uid) {
        await adminAuth.revokeRefreshTokens(uid);
      }
      return { success: true };
    } catch (error) {
      throw new Error("Failed to logout securely.");
    }
  }

  /**
   * Gets the current user by verifying their token.
   * @param {string} idToken 
   * @returns {Object} User details
   */
  async GetCurrentUser(idToken) {
    if (!adminAuth) return null;

    try {
      const decodedToken = await adminAuth.verifyIdToken(idToken);
      const userRecord = await adminAuth.getUser(decodedToken.uid);
      return userRecord;
    } catch (error) {
      return null;
    }
  }

  /**
   * Maps Firebase errors to friendly messages for client.
   */
  handleAuthError(error) {
    const code = error.code || '';
    
    switch (code) {
      case 'auth/user-not-found':
      case 'auth/wrong-password':
      case 'auth/invalid-credential':
        throw new Error('Invalid credentials'); // Generic message for security
      case 'auth/email-already-in-use':
        throw new Error('Email is already registered.');
      case 'auth/weak-password':
        throw new Error('Password is too weak.');
      case 'auth/invalid-email':
        throw new Error('Invalid email format.');
      default:
        throw error;
    }
  }
}

const authService = new AuthService();
module.exports = authService;
